"""Snapshot tests for __all__ of all public modules (Issue #1300 P1-1)."""
from __future__ import annotations

import importlib

import pytest

EXPECTED_ALL: dict[str, list[str]] = {
    "mltgnt": [
        "AgentResult",
        "AgentRunner",
        "ChatInput",
        "ChatOutput",
        "DreamSection",
        "DreamSummary",
        "Message",
        "Persona",
        "PersonaProtocol",
        "PersonaScheduler",
        "ScheduleJob",
        "__version__",
        "enqueue_and_wait",
        "enqueue_dag",
        "list_personas",
        "load_persona",
        "read_dream",
        "read_memory_by_relevance",
        "read_memory_iterative",
        "read_memory_with_sufficiency_check",
        "run_persona_prompt",
        "write_dream",
        "validate_persona",
    ],
    "mltgnt.memory": [
        "CompactionResult",
        "LlmCall",
        "LlmCallError",
        "MEMORY_CORRUPT_THRESHOLD_BYTES",
        "MEMORY_DEDUPE_SCAN_BYTES",
        "MEMORY_DEDUPE_SCAN_LINES",
        "MemoryEntry",
        "_ensure_jsonl",
        "_resolve_memory_dir",
        "_scan_tail_for_dedupe_key",
        "_search_and_score",
        "append_memory_entry",
        "assemble_entries_text",
        "compact",
        "flush_memory_commits",
        "get_collection",
        "memory_file_path",
        "needs_compaction",
        "parse_jsonl",
        "persona_memory_lock",
        "query_similar",
        "read_memory_by_relevance",
        "read_memory_iterative",
        "read_memory_preferences",
        "read_memory_tail_text",
        "read_memory_with_sufficiency_check",
        "serialize_entry",
        "tail_utf8_bytes",
        "upsert_entry",
    ],
    "mltgnt.skill": [
        "ArtifactSpec",
        "ConsumesSpec",
        "ProducesSpec",
        "SkillFile",
        "SkillMatchResult",
        "SkillMeta",
        "SkillRegistry",
        "SkillRunResult",
        "build_extra_context",
        "discover",
        "discover_bodies",
        "lint_skill_meta",
        "load",
        "match",
        "resolve_skill",
        "run",
    ],
    "mltgnt.agent": [
        "AgentResult",
        "AgentRunner",
        "DefaultReflexionEvaluator",
        "DirectAgentResult",
        "DispatchDecision",
        "MODE_DELEGATE",
        "MODE_REPLY",
        "MemoryWorkerResult",
        "Plan",
        "PlanItem",
        "PreflightContext",
        "SkillWorkerResult",
        "build_plan_prompt",
        "extract_artifact_references",
        "has_work_request",
        "is_create_request",
        "make_dispatch_decision",
        "match_deferred_promise",
        "parse_plan",
        "run_preflight",
        "should_force_delegate",
        "should_preempt_delegate",
    ],
    "mltgnt.bridges": [
        "DagStep",
        "MltgntHooks",
        "call_llm",
        "create_audit_writer",
        "enqueue_and_wait",
        "enqueue_dag",
        "files_adapter",
        "ghdag_bridge",
        "hooks_adapter",
        "llm_adapter",
        "md_read",
        "md_write",
    ],
    "mltgnt.routing": [
        "ChannelPersonaEntry",
        "RoutingRule",
        "SpacePersonaEntry",
        "TRIAGE_PROFILE_MAX_CHARS",
        "detect_nickname",
        "evaluate",
        "extract_json_object",
        "extract_triage_section",
        "find_observers",
        "find_observers_in_space",
        "load_channel_persona_map",
        "prepare_profile_for_triage",
        "resolve_persona",
        "resolve_responding_persona",
    ],
    "mltgnt.persona": [
        "Persona",
        "PersonaContext",
        "PersonaValidationError",
        "compress_heavy_to_light",
        "format_persona_body",
        "format_result_for_persona",
        "list_personas",
        "load_persona",
        "regenerate_light_block",
        "run_persona_prompt",
        "validate_persona",
    ],
    "mltgnt.interfaces": [
        "Attachment",
        "ChatInput",
        "ChatInputBase",
        "ChatOutput",
        "ChatOutputBase",
        "HistoryMessage",
        "Message",
        "PersonaFMBase",
        "PersonaProtocol",
        "SlackClientProtocol",
        "TurnHandler",
        "TurnInput",
        "TurnResult",
    ],
    "mltgnt.scheduler": [
        "PersonaScheduler",
        "ScheduleJob",
        "SchedulePaths",
        "_hash_offset",
        "atomic_write_text",
        "load_schedule_jobs",
    ],
    "mltgnt.daemon": [
        "DaemonComponent",
        "DaemonRunner",
        "PidLock",
        "SkillWatcherComponent",
    ],
    "mltgnt.config": [
        "ConversationConfig",
        "DEFAULT_WEIGHT_MAP",
        "MemoryConfig",
        "PersonaConfig",
        "SchedulerConfig",
    ],
    "mltgnt.conversation": [
        "Attachment",
        "ConversationConfig",
        "HistoryMessage",
        "TurnInput",
        "TurnResult",
        "configure",
        "fake_media",
        "get_config",
        "session_compact",
        "session_store",
        "thread_index",
        "thread_persona_store",
        "thread_queue",
    ],
    "mltgnt.conversation.session_compact": [
        "CompactionResult",
        "audit_path",
        "build_prompt",
        "compact",
        "configure",
        "configure_llm_factory",
        "estimate_tokens",
        "format_turns_for_prompt",
        "load_turns_safe",
        "needs_compaction",
    ],
    "mltgnt.conversation.session_store": [
        "SessionRecord",
        "append_turn",
        "configure",
        "configure_paths",
        "configure_resume_check",
        "gc_sessions",
        "invalidate_ledger",
        "invalidate_session",
        "latest_session",
        "load_turns",
        "lookup_ledger",
        "record_ledger_entry",
        "record_session",
        "resume_supported",
        "session_exists",
        "session_path",
        "sessions_dir",
        "storage_key",
    ],
    "mltgnt.conversation.thread_index": [
        "append_entry",
        "configure",
        "lookup_result_path",
        "register_bot_post",
        "set_post_content_writer",
        "storage_key",
        "write_post_content",
    ],
    "mltgnt.conversation.thread_persona_store": [
        "LOCK",
        "compact",
        "configure",
        "configure_on_set",
        "is_expired",
        "load",
        "set_persona",
        "ttl_days",
    ],
    "mltgnt.conversation.thread_queue": [
        "AdmitResult",
        "THREAD_QUEUE_DIR",
        "admit",
        "build_composite_instruction",
        "configure",
        "drain_to_turn_input",
        "drained_entries_meta",
        "finish_turn",
        "is_stale",
        "read_state",
        "record_job",
        "record_job_by_key",
        "set_config_provider",
        "set_lock_registry",
        "storage_key",
        "thread_queue_config",
    ],
    "mltgnt.exceptions": [
        "ConfigError",
        "DependencyError",
        "MltgntError",
    ],
}


@pytest.mark.parametrize("module_path,expected", EXPECTED_ALL.items())
def test_all_snapshot(module_path: str, expected: list[str]) -> None:
    mod = importlib.import_module(module_path)
    actual = sorted(getattr(mod, "__all__", []))
    assert actual == sorted(expected), (
        f"{module_path}.__all__ changed.\n"
        f"  Added: {set(actual) - set(expected)}\n"
        f"  Removed: {set(expected) - set(actual)}"
    )


def test_all_snapshot_covers_eighteen_modules() -> None:
    assert len(EXPECTED_ALL) == 18
